version: "3.3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=meusecret123
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - wordpress

  wordpress:
    depends_on:
      - mysql
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    environment:
      - WORDPRESS_DB_HOST=mysql-db:3306
      - WORDPRESS_DB_USER=admin
      - WORDPRESS_DB_PASSWORD=aquelasenhatop
      - WORDPRESS_DB_NAME=mydb
    volumes:
      - wordpress:/var/www/html
    networks:
      - wordpress


  webserver:
      depends_on:
        - wordpress
      image: nginx:alpine
      container_name: webserver
      volumes:
        - wordpress:/var/www/html
        - nginx:/etc/nginx/conf.d
      ports:
        - "443:443"
        - "80:80"
      networks:
        - wordpress

volumes:
  db-data:
  wordpress:
  nginx:

networks:
  wordpress:

